In [7]:
from sklearn.datasets import load_breast_cancer, load_digits
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB
import numpy as np

In [10]:
X_c, y_c = load_breast_cancer(True)
X_d, y_d = load_digits(return_X_y = True)

In [14]:
means_c = []
means_d = []
for est in [BernoulliNB(), MultinomialNB(), GaussianNB()]:
    means_c.append(cross_val_score(est, X_c, y_c).mean())
    means_d.append(cross_val_score(est, X_d, y_d).mean())
max_c = max(means_c)
max_d = max(means_d)
print max_d, means_d.index(max_d)
print max_c, means_c.index(max_c)

0.8708771489735053 1
0.9367492806089297 2


In [15]:
print X_c
print X_d

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
