In [13]:
import pandas as pd
df = pd.read_csv('SMSSpamCollection.txt', sep = '\t', header = None)
df.columns = ['cls', 'text']
df['cat'] = df.cls.apply(lambda x: 1 if x == 'spam' else 0)
df.head()

cls                                               text  cat
0   ham  Go until jurong point, crazy.. Available only ...    0
1   ham                      Ok lar... Joking wif u oni...    0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...    1
3   ham  U dun say so early hor... U c already then say...    0
4   ham  Nah I don't think he goes to usf, he lives aro...    0

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
from scipy.sparse import csr_matrix

In [23]:
cvect = CountVectorizer()
X = csr_matrix.todense(cvect.fit_transform(df.text))
print X

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [26]:
from sklearn.cross_validation import cross_val_score
from sklearn.linear_model import LogisticRegression

In [29]:
scores = cross_val_score(LogisticRegression(), X, df.cat,
                        'f1', 10)
print scores

[0.95890411 0.89855072 0.91549296 0.95833333 0.93706294 0.91304348
 0.94444444 0.92753623 0.92198582 0.95104895]


In [31]:
s_mean = scores.mean()

In [33]:
with open('ans1.txt', 'w') as f:
    f.write('%.1f' % s_mean)

In [39]:
lr = LogisticRegression()
lr.fit(X, df.cat)
to_pred = cvect.transform(
    ["FreeMsg: Txt: CALL to No: 86888 & claim your reward of 3 hours talk time to use from your phone now! Subscribe6GB",
    "FreeMsg: Txt: claim your reward of 3 hours talk time",
    "Have you visited the last lecture on physics?",
    "Have you visited the last lecture on physics? Just buy this book and you will have all materials! Only 99$",
    "Only 99$"])
pred = lr.predict(to_pred)

In [42]:
with open('ans2.txt', 'w') as f:
    f.write(" ".join([str(x) for x in pred]))

In [43]:
from sklearn.pipeline import Pipeline

In [47]:
scores = []
for gr in [(2,2), (3,3), (1,3)]:
    scores.append(
        cross_val_score(
            Pipeline([('transformer',CountVectorizer(ngram_range = gr)),
                     ('classifier',LogisticRegression())]),
            df.text, df.cat, 'f1', 10).mean())
print scores

[0.8224220664187133, 0.7250161555467377, 0.9251382558648837]


In [49]:
with open('ans3.txt', 'w') as f:
    f.write(" ".join(['%.2f'%x for x in scores]))

In [52]:
from sklearn.naive_bayes import MultinomialNB
scores = []
for gr in [(2,2), (3,3), (1,3)]:
    cv3 = CountVectorizer(ngram_range = gr)
    X = cv3.fit_transform(df.text)
    scores.append(
        cross_val_score(MultinomialNB(), X, df.cat,
                        'f1', 10).mean())
print scores

[0.6455015177985443, 0.37871948524573595, 0.8884859656061002]


In [53]:
with open('ans4.txt', 'w') as f:
    f.write(" ".join(['%.2f'%x for x in scores]))

In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer
ctf = TfidfVectorizer()
X = csr_matrix.todense(ctf.fit_transform(df.text))
print X

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [55]:
scores = cross_val_score(LogisticRegression(), X, df.cat,
                        'f1', 10)
print scores.mean()

0.8528599554172456


In [57]:
with open('ans5.txt', 'w') as f:
    f.write('-1')